import "./globals.css";
import Navigation from "../components/Navigation.jsx";
import { Ubuntu } from "next/font/google";

export const metadata = {
  title: "Tropical nature",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Navigation />
        <div className="max-w-6xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
